export const data = {
  scoreItems: [
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
    {
      number: 1,
      playerName: "Alice",
      gameName: "Chess",
      score: 300,
    },
    {
      number: 2,
      playerName: "Bob",
      gameName: "Soccer",
      score: 150,
    },
    {
      number: 3,
      playerName: "Charlie",
      gameName: "Tennis",
      score: 200,
    },
    {
      number: 4,
      playerName: "Diana",
      gameName: "Basketball",
      score: 180,
    },
  ],
};
